### ISSUE TITLE
Communication Documentation

### ISSUE THREAD

**Issue by ColePBryan** [LogicAnalyzer/analyzer#11]
- module overview
- interface definitions
- module functionality
  - input requirements
  - output requirements
- inputs and outputs summary

**Comment by alexnorell** [comment]
https://sigrok.org/wiki/Protocol_decoder_API

**Comment by alexnorell** [comment]
https://github.com/sigrokproject/libsigrok/tree/master/src/hardware/openbench-logic-sniffer

**Comment by alexnorell** [comment]
Adding a new hardware driver
----------------------------

The simple, scripted way (recommended):
---------------------------------------

Use the 'new-driver' script from the sigrok-util repo:

 $ git clone git://sigrok.org/sigrok-util
 $ cd sigrok-util/source
 $ ./new-driver "Tondaj SL-814"

The example above generates a patch file against the current libsigrok
development git tree which adds a simple "stub" driver for your device
(the Tondaj SL-814 sound level meter in this case).

You can apply it like this:

 $ cd libsigrok
 $ git am 0001-tondaj-sl-814-Initial-driver-skeleton.patch

You can now edit the files in src/hardware/tondaj-sl-814 as needed
and implement your driver based on the skeleton files there. That means your
patch submission later will consist of at least two patches: the initial one
adding the skeleton driver, and one or more additional patches that actually
implement the respective driver code.


The manual way:
---------------

This is a rough overview of what you need to do in order to add a new driver
(using the Tondaj SL-814 device as example). It's basically what the
'new-driver' script (see above) does for you:

 - Makefile.am: Add HW_TONDAJ_SL_814 and add to libsigrok_la_SOURCES.
 - configure.ac: Add a DRIVER() and DRIVER2() call.
 - src/drivers.c: Add a tondaj_sl_814_driver_info entry in two places.
 - src/hardware/tondaj-sl-814/ directory: Add api.c, protocol.c, protocol.h.

See existing drivers or the 'new-driver' output for the details.
